# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy frontend

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - run: npm ci
    - run: CI=false npm run build --if-present
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: 'frontend-artifact'
        path: 'frontend/build'
        
    - name: Prepare build for deployment
      run: |
        cd build
        mv static/* .
        rm -rf static
        
    - name: RSync deploy
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr
        path: frontend/build/
        remote_path: ${{ secrets.DEPLOY_FRONTEND_TARGET }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_SSH_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
